name: Build and Test Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t mon-app-python .
      - name: Test Docker image
        run: |
          docker run -d --name test-app -p 5000:5000 mon-app-python
          sleep 5
          curl -f http://localhost:5000/health
          docker stop test-app
